import React from 'react'
import s from './index.scss'
import MountainPage from '../../components/mountain-page'
import TokenGenerationSignup from 'components/token-generation-signup'
import ProgressBar from 'components/progress-bar'
import Card from '../../components/card'

export default function Info({ history, ...rest }) {
  return (
    <MountainPage>
      <ProgressBar />
      <Card>
        <div className={s['description']}>
          <p className={s['featured']}>
            C4Coin invites everyone to participate in our initial token
            generation event!
          </p>
          <p>
            CO2KNs are equivalent to one carbon credit. Unlike traditional
            carbon credits, they can be used on the network to generate security
            and mine C4Coin.
          </p>
          <p>
            If you own or have retired carbon credits, redeem your retirement
            recipts! If you’re new to the carbon market, you can purchase carbon
            credits and automatically earn CO2KNs, through our partnership with
            Carbon Credit Capital (CCC)
          </p>
          <p>
            The traditional Initial Coin Offering (ICO) process is not a viable
            option for C4Coin. From a philosophical perspective, the founding
            team is opposed to pre-mining utility tokens. Alongside regulatory
            concerns, this decision prevents us from selling C4Coins. CO2KNs
            also cannot be sold in an ICO, as they represent carbon offsets and
            must be generated by verifiable environmental work.
          </p>
          <p>
            <strong>
              If you{"'"}ve participated in the carbon markets before
            </strong>, we{"'"}re offering an opportunity to be rewarded for that
            work. Existing receipts documented in Markit can be redeemed for
            CO2KNs. Click
            {'"'}Redeem Receipts{'"'} below to get started.
          </p>
          <p>
            <strong>If you{"'"}re unfamiliar with carbon markets</strong>, we{
              "'"
            }re making it easy to get involved. Our partner, Carbon Credit
            Capital, is a company with over 10 years of experience helping
            clients conduct retirement transactions. CCC is leveraging their
            knowledge to allow you to seamlessly purchase existing carbon
            credits and automatically claim them as CO2KNs. Click {'“'}purchase
            new credits{'"'} below to get started.
          </p>
          <p>
            While CCC is making its retirement transaction services available
            through this partnership, Markit receipts from any carbon brokerage
            will be accepted. For Non-CCC credits, fill out the {'"'}Redeem
            Recepits{'"'} form.
          </p>
        </div>
        <TokenGenerationSignup history={history} styleSheet={s} />
      </Card>
    </MountainPage>
  )
}
